### PR TITLE
Fix/339 bug update exit code if recursed directory contains errors

### LINKED ISSUE #339: [BUG] Update Exit Code if Recursed Directory Contains Errors
Status exit code returns 0 when errors are present in derivative/recursed bids dataset.

### PR DESCRIPTION
**Pull request by bendhouseart**
A nested/derivatives bids dataset returns a 0 exit code even if it's evaluated as invalid, this PR sets the exit code to non-zero in that case.

### CODE REVIEW

File: changelog.d/20260116_093212_28850131+bendhouseart_339_bug_update_exit_code_if_recursed_directory_contains_errors.md [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+
+- A bullet item for the Changed category.
+
+-->
+### Fixed
+
+- exit code returns non-zero status for invalid derivative datasets
+when -r/--recursive flag is used
+
+-->
```
Comment (effigies) [inline changelog.d/20260116_093212_28850131+bendhouseart_339_bug_update_exit_code_if_recursed_directory_contains_errors.md]:
```suggestion
- Exit with a non-zero exit code if nested datasets are validated and found to have errors.

```

**Comment by effigies** [comment]
What about a simple boolean function to find the first error and stop?

Here's a quick function I haven't tested:

```ts
export function detectErrors(result: ValidationResult): boolean {
  return result.issues.get({ severity: 'error' }).length > 0 ||
    Object.values(result.derivativesSummary ?? {}).some((res) => detectErrors(res))
}
```

**Comment by bendhouseart** [comment]
> What about a simple boolean function to find the first error and stop?
> 
> Here's a quick function I haven't tested:
> 
> ```ts
> export function detectErrors(result: ValidationResult): boolean {
>   return result.issues.get({ severity: 'error' }).length > 0 ||
>     Object.values(result.derivativesSummary ?? {}).some((res) => detectErrors(res))
> }
> ```

I like where your head's at.

**Comment by bendhouseart** [comment]
ohh boo, now my coverage went down.

File: local-test [hunk 2]
```diff
@@ -0,0 +1,4 @@
+#!/usr/bin/env -S deno test --allow-read --allow-write --allow-env --allow-run --allow-net --parallel --node-modules-dir=auto  --coverage=cov/ src/ 
+// This script runs the local copy of the validator, intended as a development aid.
+// You generally should run `deno run -A jsr:@bids/validator`
```
Comment (bendhouseart) [inline local-test]:
```suggestion
# script to run tests locally and save some CI time
```

File: local-test [hunk 3]
```diff
@@ -0,0 +1,2 @@
+# script to run tests locally and save some CI time
+`deno test --allow-read --allow-write --allow-env --allow-run --allow-net --parallel --node-modules-dir=auto  --coverage=cov/ src/`
```
Comment (effigies) [inline local-test]:
```suggestion
#!/bin/sh
# script to run tests locally and save some CI time
deno test --allow-read --allow-write --allow-env --allow-run --allow-net --parallel --node-modules-dir=auto  --coverage=cov/ src/
```

**Review by effigies — APPROVED** [review]
Small cleanups
